<?php


class AttendanceView extends Attendance {
   public function getLecturerAttendances()
   {
       return parent::getLecturerAttendances(); // TODO: Change the autogenerated stub
   }

   public function getAttendanceForThisLecturer($lecturerID)
   {
       return parent::getAttendanceForThisLecturer($lecturerID); // TODO: Change the autogenerated stub
   }

   public function getAttendanceForThisStudent($studentID)
   {
       return parent::getAttendanceForThisStudent($studentID); // TODO: Change the autogenerated stub
   }

    public function countAttendancesForThisLecturer($lecturerID)
   {
       return parent::countAttendancesForThisLecturer($lecturerID); // TODO: Change the autogenerated stub
   }

   public function countPresenceForThisLecturer($lecturerID)
   {
       return parent::countPresenceForThisLecturer($lecturerID); // TODO: Change the autogenerated stub
   }

   public function countAbsenceForThisLecturer($lecturerID)
   {
       return parent::countAbsenceForThisLecturer($lecturerID); // TODO: Change the autogenerated stub
   }

    public function countAttendancesForThisStudent($id)
    {
        return parent::countAttendancesForThisStudent($id); // TODO: Change the autogenerated stub
    }

    public function countPresenceForThisStudent($id)
    {
        return parent::countPresenceForThisStudent($id); // TODO: Change the autogenerated stub
    }

    public function countAbsenceForThisStudent($id)
    {
        return parent::countAbsenceForThisStudent($id); // TODO: Change the autogenerated stub
    }

    public function countLecturerAttendanceForToday()
    {
        return parent::countLecturerAttendanceForToday(); // TODO: Change the autogenerated stub
    }

    public function countStudentAttendanceForToday()
    {
        return parent::countStudentAttendanceForToday(); // TODO: Change the autogenerated stub
    }

    public function countStudentPresenceForToday()
    {
        return parent::countStudentPresenceForToday(); // TODO: Change the autogenerated stub
    }

    public function countLecturerPresenceForToday()
    {
        return parent::countLecturerPresenceForToday(); // TODO: Change the autogenerated stub
    }

    public function countAllLecturerAbsence()
    {
        return parent::countAllLecturerAbsence(); // TODO: Change the autogenerated stub
    }

    public function countAllStudentAbsence()
    {
        return parent::countAllStudentAbsence(); // TODO: Change the autogenerated stub
    }

    public function countAttendanceForLecturers()
    {
        return parent::countAttendanceForLecturers(); // TODO: Change the autogenerated stub
    }

    public function countAllStudentPresence()
    {
        return parent::countAllStudentPresence(); // TODO: Change the autogenerated stub
    }

    public function countAllLecturerPresence()
    {
        return parent::countAllLecturerPresence(); // TODO: Change the autogenerated stub
    }

    public function countAttendanceForStudents()
    {
        return parent::countAttendanceForStudents(); // TODO: Change the autogenerated stub
    }


}