<?php
    class CourseAllocationView extends CourseAllocation {
        public function getPrograms()
        {
            return parent::getPrograms(); // TODO: Change the autogenerated stub
        }

        public function getCoursesForThisProgram($id)
        {
            return parent::getCoursesForThisProgram($id); // TODO: Change the autogenerated stub
        }

        public function getAllocations()
        {
            return parent::getAllocations(); // TODO: Change the autogenerated stub
        }

        public function countAllocations()
       {
           return parent::countAllocations(); // TODO: Change the autogenerated stub
       }
    }
?>