<?php
    class CoursesAndProgramsController extends CourseAllocation {

        public function setAllocation($programID, $courseID, $unitCode)
        {
            return parent::setAllocation($programID, $courseID, $unitCode); // TODO: Change the autogenerated stub
        }
        public function deleteAllocation($courseID, $programID)
        {
            return parent::deleteAllocation($courseID, $programID); // TODO: Change the autogenerated stub
        }

    }
?>