<?php
    class CoursesController extends Courses{
       public function setCourse($id, $name, $level, $credit)
       {
           return parent::setCourse($id, $name, $level, $credit); // TODO: Change the autogenerated stub
       }

       public function editCourse($id, $name, $level, $credit)
       {
           return parent::editCourse($id, $name, $level, $credit); // TODO: Change the autogenerated stub
       }

       public function deleteCourse($id)
       {
           return parent::deleteCourse($id); // TODO: Change the autogenerated stub
       }

    }
?>