<?php
    class CoursesView extends Courses{
      public function getAllCourses()
      {
          return parent::getAllCourses(); // TODO: Change the autogenerated stub
      }

      public function getCourse($id)
      {
          return parent::getCourse($id); // TODO: Change the autogenerated stub
      }

        public function countCourses()
      {
          return parent::countCourses(); // TODO: Change the autogenerated stub
      }
    }
?>