<?php
    class LecturersView extends Lecturers{

       public function getAllLecturers()
       {
           return parent::getAllLecturers(); // TODO: Change the autogenerated stub
       }

       public function getLecturer($id)
       {
           return parent::getLecturer($id); // TODO: Change the autogenerated stub
       }

        public function countLecturers()
       {
           return parent::countLecturers(); // TODO: Change the autogenerated stub
       }
    }
?>