<?php


class LecturersAndCoursesView extends LecturersAndCourses {
   public function getAllocationsForThisLecturer($lecturerID)
   {
       return parent::getAllocationsForThisLecturer($lecturerID); // TODO: Change the autogenerated stub
   }

   public function getAllocation($lecturerID, $courseID)
   {
       return parent::getAllocation($lecturerID, $courseID); // TODO: Change the autogenerated stub
   }

    public function countAllocations()
   {
       return parent::countAllocations(); // TODO: Change the autogenerated stub
   }

   public function getLecturers()
   {
       return parent::getLecturers(); // TODO: Change the autogenerated stub
   }

   public function getCoursesForThisLecturer($id)
   {
       return parent::getCoursesForThisLecturer($id); // TODO: Change the autogenerated stub
   }

   public function getDays()
   {
       return parent::getDays(); // TODO: Change the autogenerated stub
   }

   public function getCourseForThisLecturer($id, $course)
   {
       return parent::getCourseForThisLecturer($id, $course); // TODO: Change the autogenerated stub
   }
}