<?php


class LecturersAndCoursesController extends LecturersAndCourses {
    public function setAllocation($lecturerID, $courseID, $day, $timeRange, $room)
    {
        return parent::setAllocation($lecturerID, $courseID, $day, $timeRange, $room); // TODO: Change the autogenerated stub
    }

   public function deleteAllocation($courseID, $lecturerID, $timeRange, $day)
   {
       return parent::deleteAllocation($courseID, $lecturerID, $timeRange, $day); // TODO: Change the autogenerated stub
   }


}