<?php
    class ProgramsController extends Programs {
       public function setProgram($id, $name, $tuition)
       {
           return parent::setProgram($id, $name, $tuition); // TODO: Change the autogenerated stub
       }

       public function editProgram($id, $name, $tuition)
       {
          return parent::editProgram($id, $name, $tuition); // TODO: Change the autogenerated stub
       }

       public function deleteProgram($id)
       {
           return parent::deleteProgram($id); // TODO: Change the autogenerated stub
       }


    }
?>