<?php
    class ProgramsView extends Programs {
        public function getAllPrograms()
        {
            return parent::getAllPrograms(); // TODO: Change the autogenerated stub
        }

        public function getProgram($id)
        {
            return parent::getProgram($id); // TODO: Change the autogenerated stub
        }

        public function countPrograms()
        {
            return parent::countPrograms(); // TODO: Change the autogenerated stub
        }
    }
?>