<?php
    class StudentsView extends Students{
        public function getAllStudents()
        {
            return parent::getAllStudents(); // TODO: Change the autogenerated stub
        }

        public function getCertifiedStudents()
        {
            return parent::getCertifiedStudents(); // TODO: Change the autogenerated stub
        }

        public function getUncertifiedStudents()
        {
            return parent::getUncertifiedStudents(); // TODO: Change the autogenerated stub
        }

        public function getStudentsForThisProgram($program)
        {
            return parent::getStudentsForThisProgram($program); // TODO: Change the autogenerated stub
        }

        public function getStudentsForThisProgramAtThisIntake($program, $intake)
        {
            return parent::getStudentsForThisProgramAtThisIntake($program, $intake); // TODO: Change the autogenerated stub
        }

        public function countStudents()
        {
            return parent::countStudents(); // TODO: Change the autogenerated stub
        }

        public function getInfoForThisStudent($id)
        {
            return parent::getInfoForThisStudent($id); // TODO: Change the autogenerated stub
        }

        public function getAllStudentsForThisIntake($intake)
        {
            return parent::getAllStudentsForThisIntake($intake); // TODO: Change the autogenerated stub
        }

        public function getCertifiedStudentsForThisIntake($intake)
        {
            return parent::getCertifiedStudentsForThisIntake($intake); // TODO: Change the autogenerated stub
        }

        public function getUncertifiedStudentsForThisIntake($intake)
        {
            return parent::getUncertifiedStudentsForThisIntake($intake); // TODO: Change the autogenerated stub
        }

        public function getDetailsForThisStudent($id)
        {
            return parent::getDetailsForThisStudent($id); // TODO: Change the autogenerated stub
        }

        public function getNumberOfCollectedCertificatesToday()
        {
            return parent::getNumberOfCollectedCertificatesToday(); // TODO: Change the autogenerated stub
        }
    }
?>