<?php
    class TimeAndDaysController extends TimeAndDays {
      public function setDay($day)
      {
          return parent::setDay($day); // TODO: Change the autogenerated stub
      }

      public function setTime($startTime, $endTime)
      {
          return parent::setTime($startTime, $endTime); // TODO: Change the autogenerated stub
      }

        public function deleteDay($id)
      {
          return parent::deleteDay($id); // TODO: Change the autogenerated stub
      }

      public function deleteTimeRange($id)
      {
          return parent::deleteTimeRange($id); // TODO: Change the autogenerated stub
      }

    }
?>