<?php
    class TimeAndDaysView extends TimeAndDays {
         public function getDays()
         {
             return parent::getDays(); // TODO: Change the autogenerated stub
         }

         public function getDay($dayID)
         {
             return parent::getDay($dayID); // TODO: Change the autogenerated stub
         }

        public function getTimeRange($rangeID)
         {
             return parent::getTimeRange($rangeID); // TODO: Change the autogenerated stub
         }

        public function getTimeRanges()
         {
             return parent::getTimeRanges(); // TODO: Change the autogenerated stub
         }

    }
?>