<?php 
    class UsersView extends Users{
        public function checkCredentials($username, $passwd){
            return $this->checkUserCredentials($username, $passwd);
        }

        public function getUsers()
        {
            return parent::getUsers(); // TODO: Change the autogenerated stub
        }

        public function countUsers()
        {
            return parent::countUsers(); // TODO: Change the autogenerated stub
        }

        public function getUser($id)
        {
            return parent::getUser($id); // TODO: Change the autogenerated stub
        }
    }
?>